### ISSUE TITLE
End of input at character 0 of

### ISSUE THREAD

**Issue by pedrojb** [Tealium/android-library#5]
Hi, I noticed this error when i have call method init on Tealium.

Tealium-4.1.1﹕ End of input at character 0 of
    org.json.JSONException: End of input at character 0 of
            at org.json.JSONTokener.syntaxError(JSONTokener.java:450)
            at org.json.JSONTokener.nextValue(JSONTokener.java:97)
            at org.json.JSONObject.<init>(JSONObject.java:156)
            at org.json.JSONObject.<init>(JSONObject.java:173)
            at com.tealium.library.aj.receivedConfig(Unknown Source)
            at com.tealium.library.JSInterface.receivedConfig(Unknown Source)
            at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
            at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:211)
            at android.os.HandlerThread.run(HandlerThread.java:61)

Can you help me? 

Thanks, Pedro.

**Comment by ChadHartman** [comment]
Hi, I'd love to help. 

If you're using an *account-profile-environment* other than *tealiummobile-demo-dev*, can you reach out to your account manager? It sounds like an error in TiQ configuration. 

Otherwise, I'll need a little more information: 

* Is this error in a sample project or a custom one you've built? 
* What Android device are you seeing this error on?
* What version of Android does the device have?
* Does this error occur every app launch?

**Comment by ChadHartman** [comment]
Closing due to lack of feedback

**Comment by drschilling** [comment]
Same issue here.

10-14 21:27:25.362 3712-3882/br.com.tvglobo.globoplayandroid A/Tealium-4.1.4: End of input at character 0 of 
10-14 21:27:25.362 3712-3882/br.com.tvglobo.globoplayandroid A/Tealium-4.1.4: org.json.JSONException: End of input at character 0 of 
10-14 21:27:25.362 3712-3882/br.com.tvglobo.globoplayandroid A/Tealium-4.1.4:     at org.json.JSONTokener.syntaxError(JSONTokener.java:450)
10-14 21:27:25.362 3712-3882/br.com.tvglobo.globoplayandroid A/Tealium-4.1.4:     at org.json.JSONTokener.nextValue(JSONTokener.java:97)
10-14 21:27:25.362 3712-3882/br.com.tvglobo.globoplayandroid A/Tealium-4.1.4:     at org.json.JSONObject.<init>(JSONObject.java:155)
10-14 21:27:25.362 3712-3882/br.com.tvglobo.globoplayandroid A/Tealium-4.1.4:     at org.json.JSONObject.<init>(JSONObject.java:172)
10-14 21:27:25.362 3712-3882/br.com.tvglobo.globoplayandroid A/Tealium-4.1.4:     at com.tealium.library.aj.receivedConfig(Unknown Source)
10-14 21:27:25.362 3712-3882/br.com.tvglobo.globoplayandroid A/Tealium-4.1.4:     at com.tealium.library.JSInterface.receivedConfig(Unknown Source)
10-14 21:27:25.362 3712-3882/br.com.tvglobo.globoplayandroid A/Tealium-4.1.4:     at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
10-14 21:27:25.362 3712-3882/br.com.tvglobo.globoplayandroid A/Tealium-4.1.4:     at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:27)
10-14 21:27:25.362 3712-3882/br.com.tvglobo.globoplayandroid A/Tealium-4.1.4:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-14 21:27:25.362 3712-3882/br.com.tvglobo.globoplayandroid A/Tealium-4.1.4:     at android.os.Looper.loop(Looper.java:136)
10-14 21:27:25.362 3712-3882/br.com.tvglobo.globoplayandroid A/Tealium-4.1.4:     at android.os.HandlerThread.run(HandlerThread.java:61).

Answering the questions:
Is this error in a sample project or a custom one you've built? R: My own project. 
What Android device are you seeing this error on? R: Currently using a Motorola Moto Maxx 
What version of Android does the device have? R: Android 5.0.2
Does this error occur every app launch? R: Yes it does

**Comment by ChadHartman** [comment]
@drschilling, really appreciate the feedback. This is typically indicative of "mobile" not being enabled in your TealiumIQ account. If "mobile" is already enabled (accessible through publish settings), please contact your account manager.

**Comment by drschilling** [comment]
Thank you, Chad! We resolved that previous issue. Since we are using the full version of the library, is there a way to disable the Mobile Companion to appear to the a regular user and still have the publish settings set to "mobile"?

**Comment by ChadHartman** [comment]
@drschilling I'm sorry, I don't quite follow what you mean by 

> publish settings set to "mobile"

but if you wish to turn off mobile companion it may be done in the publish settings under "Debugging":
![screen shot 2015-10-22 at 9 36 21 am](https://cloud.githubusercontent.com/assets/5520913/10671611/788a01e2-78a0-11e5-993b-9743e79f48c0.png)

**Comment by drschilling** [comment]
Sorry if I was not clear in my early explanation. I am facing two issues The first question has relation with the dispatch of events. When using a Motorola Moto Maxx with Android 5.0.2 the events are always dispatching with queues (even if the device is connected to a functional Wifi). And my other issue relays on tracking automatic events. Even using the full version of the library it seems that the automatic tracking of the views is not working.

**Comment by ChadHartman** [comment]
> the events are always dispatching with queues (even if the device is connected to a functional Wifi).

The first couple of calls tend to get queued because configuration data had not yet downloaded. As for others, there is a variety of reasons such as batch sizes and whether battery saver is enabled.

> And my other issue relays on tracking automatic events. Even using the full version of the library it seems that the automatic tracking of the views is not working.

The library uses ```Activity.onResume()``` for "view events". So if you have a different application "view" or "page" paradigm, those would have to be manually added.
