### ISSUE TITLE
Configuring dispatch queue size

### ISSUE THREAD

**Issue by ataulm** [Tealium/android-library#6]
Is it possible to set the size of the offline queue for events before a network call is made? i.e. even if the device has a network connection, I don't want it to send events as soon as it gets them - I want to send x events at a time.

In addition, is there a way to say "sendAllQueuedEventsNow"?

I couldn't find these on the documentation on Github - only a reference to the mobile companion.

Thanks

**Comment by ChadHartman** [comment]
There is no "sendAllQueuedEventsNow" method. The library, however, does have numerous sending configuration options. In [TealiumIQ](https://my.tealiumiq.com) there are publish settings with batching options:

* Log into TealiumIQ
* Select "Save/Publish" 
* On the window that appears, select "Configure Publish Settings..." 
* Select the "Mobile Library Publishing" tab
 * "Activate Mobile Library" if not activated. 
* Under the "Batching" section you can select your desired batch size. 
 * 1 by default.
